version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
  nginx:
      image: nginx:stable-alpine
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./crt:/etc/nginx/certs
      ports:
        - 4443:4443